---
  - src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.13"
    name: clickhouse

  - src: git@github.com:gaidarvu/vector-role.git
    scm: git
    version: "v1.1.0"
    name: vector

  - src: git@github.com:gaidarvu/lighthouse-role.git
    scm: git
    version: "v1.2.1"
    name: lighthouse
    
  - src: git@github.com:gaidarvu/nginx-role.git
    scm: git
    version: "v1.1.0"
    name: nginx
  