---
- name: Install Clickhouse
  become: true
  hosts: clickhouse
  roles:
    - clickhouse

- name: Install Vector
  become: true
  hosts: vector
  roles:
    - vector

- name: Install LightHouse
  become: true
  hosts: lighthouse
  roles:
    - lighthouse
