---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - block:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.noarch.rpm"
            dest: "./{{ item }}-{{ clickhouse_version }}.rpm"
          with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm"
            dest: "./clickhouse-common-static-{{ clickhouse_version }}.rpm"
    - name: Install clickhouse packages
      become: true
      ansible.builtin.yum:
        name:
          - clickhouse-common-static-{{ clickhouse_version }}.rpm
          - clickhouse-client-{{ clickhouse_version }}.rpm
          - clickhouse-server-{{ clickhouse_version }}.rpm
      notify: Start clickhouse service
    - name: Flush handlers
      meta: flush_handlers
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0

    



mkdir -p vector
wget https://packages.timber.io/vector/0.42.0/vector-0.42.0-x86_64-unknown-linux-musl.tar.gz
tar xzf - -C vector --strip-components=2
cp bin/vector /usr/bin/
mkdir -p /etc/vector
cp config/vector.yaml /etc/vector/
cp etc/systemd/vector.service /etc/systemd/system/
sudo systemctl daemon-reload
sudo systemctl restart vector

User=vector
Group=vector
ExecStart=/usr/bin/vector --config /etc/vector/vector.yaml




    # - name: Get Vector
    #   get_url:
    #     url: https://raw.githubusercontent.com/vectordotdev/vector/master/distribution/install.sh
    #     dest: /tmp/install.sh
    #     mode: 0755
    
    # - name: Setup Vector
    #   command: /tmp/install.sh
