---
driver:
  name: podman
lint: |
  ansible-lint .
  yamllint .
platforms:
  - name: python
    image: python:latest
    pre_build_image: true
verifier:
  name: ansible
scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - destroy