---
driver:
  name: podman
lint: |
  ansible-lint .
  yamllint .
platforms:
  - name: CentOS7
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
verifier:
  name: ansible
scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - destroy