---
all:
  vars:
    remote_user: gaidar
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 158.160.43.230
vector:
  hosts:
    vector-01:
      ansible_host: 158.160.52.137
lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 158.160.51.204